apps:

- name: exercise-28.2
  script: index.js
  watch: true
  exec_mode: cluster
  instances: 1
  max_memory_restart: 100M
  autorestart: true
  env:
    ENVIRONMENT: Default
  env_prod:
    ENVIRONMENT: Production
  env_homolog:
    PORT: 3002
    ENVIRONMENT: Homolog

- name: exercise-28.2-second-instance
  script: index.js
  exec_mode: fork
  env:
    ENVIRONMENT: Default second instance
    PORT: 3003
  env_prod:
    ENVIRONMENT: Production second instance
    PORT: 3003