apps:

- name: exercise-28.2
  script: index.js
  watch: true
  exec_mode: cluster
  instances: max
  max_memory_restart: 100M
  env_prod:
    ENVIRONMENT: Production
  env_homolog:
    PORT: 3002
    ENVIRONMENT: Homolog
